apiVersion: v1
description: Kubeflow PytorchJob integration with Polyaxon
name: pytorchjob
version: 1.0.1
keywords:
  - deep learning
  - a.i.
  - machine learning
  - infrastructure
sources:
  - https://github.com/polyaxon
home: https://polyaxon.com
icon: https://polyaxon.com/img/icon.png
maintainers:
  - name: Polyaxon
    email: contact@polyaxon.com
    url: polyaxon.com
