{{- if .Values.beat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-beat
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-beat
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreWorker" . | indent 4 }}
spec:
  replicas: {{ .Values.beat.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-beat
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 8 }}
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-beat
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreWorker" . | indent 8 }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-beat
        image: "{{ .Values.beat.image }}:{{ .Values.beat.imageTag }}"
        imagePullPolicy: {{ .Values.beat.imagePullPolicy }}
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
        livenessProbe:
          failureThreshold: 10
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 30
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.beat.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.beat.resources.limits | indent 12 }}
          {{- end }}
{{- end }}
