{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-operator
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 4 }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.agent }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.agent }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 8 }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-operator
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.agent }}
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.operator.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}-operator
        image: "{{ .Values.operator.image }}:{{ .Values.operator.imageTag }}"
        imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
        command:
        - /manager
        args:
        - --enable-leader-election
        envFrom:
{{ include "config.envFrom.agent" . | indent 8 }}
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.proxies" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.operator.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.operator.resources.limits | indent 12 }}
          {{- end }}
{{- end }}
