{{- if .Values.externalServices.postgresql.pgbouncer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-pgbouncer
  labels:
    app: {{ template "polyaxon.fullname" . }}-pgbouncer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.metrics }}
    role: {{ .Values.roles.worker }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-pgbouncer
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.worker }}
    app.kubernetes.io/managed-by: "helm"
spec:
  type: NodePort
  ports:
  - port: {{ template "pgsql.port" . }}
    targetPort: {{ template "pgsql.port" . }}
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-pgbouncer
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
