{{- if and .Values.scheduler.enabled (eq .Values.broker "rabbitmq") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-exchange"
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-create-exchange
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreHooks" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "15"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-create-exchange"
      labels:
        app: {{ template "polyaxon.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      restartPolicy: Never
      activeDeadlineSeconds: 360
      containers:
      - name: create-exchange-job
        image: "{{ .Values.hooks.image }}:{{ .Values.hooks.imageTag }}"
        imagePullPolicy: {{ .Values.hooks.imagePullPolicy }}
        args: ["create_exchange"]
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.manageEnvs" . | indent 8 }}
{{- end }}
