deploymentType: minikube

rbac:
  enabled: false

ingress:
  enabled: false

gateway:
  resources:
    requests:
      memory: 40Mi
      cpu: 20m
  service:
    type: NodePort


user:
  username: travis
  password: travis

postgresql:
  resources:
    requests:
      memory: 40Mi
      cpu: 20m

broker: rabbitmq

rabbitmq-ha:
  enabled: true
  resources:
    requests:
      memory: 40Mi
      cpu: 20m

api:
  imagePullPolicy: Always
  resources:
    requests:
      memory: 80Mi
      cpu: 30m

streams:
  imagePullPolicy: Always
  resources:
    requests:
      memory: 80Mi
      cpu: 30m

scheduler:
  enabled: true
  imagePullPolicy: Always
  resources:
    requests:
      memory: 80Mi
      cpu: 30m

environment: testing
