deploymentType: minikube

rbac:
  enabled: false

ingress:
  enabled: false

gateway:
  resources:
    requests:
      memory: 40Mi
      cpu: 20m
  service:
    type: NodePort

user:
  username: travis
  password: travis

postgresql:
  resources:
    requests:
      memory: 40Mi
      cpu: 20m

api:
  imagePullPolicy: Always
  resources:
    requests:
      memory: 80Mi
      cpu: 30m

streams:
  imagePullPolicy: Always
  resources:
    requests:
      memory: 80Mi
      cpu: 30m

artifactsStore:
  name: test
  kind: host_path
  schema:
    mountPath: "/tmp/artifacts"
    hostPath: "/tmp/artifacts"

connections:
- name: foo
  kind: host_path
  schema:
    mountPath: "/tmp/foo"
    hostPath: "/tmp/foo"
- name: bar
  kind: host_path
  schema:
    mountPath: "/tmp/bar"
    hostPath: "/tmp/bar"

environment: testing
