deploymentChart: agent
deploymentType: kubernetes
namespace: polyaxon
limitResources: false

rbac:
  enabled: true

types:
  agent: "polyaxon-agent"

roles:
  config: "polyaxon-config"
  agent: "polyaxon-agent"

externalServices:
  api:
    host:
    port:

auth:
  enabled: true
  external:
  useResolver: true

gateway:
  enabled: true
  image: polyaxon/polyaxon-gateway
  imageTag: 1.0.9
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 50Mi

  service:
    name: gateway
    type: ClusterIP
    port: 80
    targetPort: 80
    nodePort: 31833
    annotations: {}

streams:
  enabled: true
  image: polyaxon/polyaxon-streams
  imageTag: 1.0.9
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 128m
      memory: 300Mi

  service:
    name: streams
    type: ClusterIP
    port: 80
    targetPort: 80
    nodePort: 31822
    annotations: {}

  hpa:
    enabled: false
    cputhreshold: 70
    minpods: 1
    maxpods: 4

init:
  image: polyaxon/polyaxon-init
  imageTag: 1.0.9
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 100Mi

sidecar:
  image: polyaxon/polyaxon-sidecar
  imageTag: 1.0.9
  imagePullPolicy: Always
  sleepInterval: 10
  syncInterval: 10
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 100Mi

agent:
  token:
  instance:
  enabled: true
  image: polyaxon/polyaxon-agent
  imageTag: 1.0.9
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 100Mi

operator:
  enabled: true
  image: polyaxon/polyaxon-operator
  imageTag: 1.0.9
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 50Mi

securityContext:
  enabled: false
  user: 2222
  group: 2222

nodeSelector: {}
tolerations: []
affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: type
              operator: In
              values:
              - "polyaxon-core"
          topologyKey: "kubernetes.io/hostname"

imagePullSecrets: []

artifactsStore:
connections: []
notificationConnections: []

# Include helm chart release revision
includeChartRevision: false
